name: Build and publish

on:
  push:
    branches:
      - main
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: tag and publish  
        run: |
          pip install poetry
          git config user.name github-actions
          git config user.email github-actions@github.com
          version=v$(poetry version -s)
          if ! git rev-parse $version >/dev/null 2>&1; then
            git tag $version
            git push --tags
            poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
            poetry publish
          fi
